name: plunging-criterion
dependencies:
  - python = 3.8
  - scipy >= 1.6.0
  - numpy >= 1.20.0
  - matplotlib >= 3.3.0
  - ipywidgets >= 7.6
  - jupyterlab >= 3.0.0
  - xarray
  - netCDF4
  - dask
  - pip
  - tqdm
  - pip:
    - expectexception
    - ipympl